spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ***REMOVED***
            clientSecret: ***REMOVED***
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
              - openid
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenUri: https://oauth2.googleapis.com/token
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            userNameAttribute: sub
            jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
  datasource:
    url: jdbc:mysql://localhost:3306/human_capital_management_dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web: DEBUG