server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${CLIENT_ID}
            clientSecret: ${CLIENT_SECRET}
            redirectUri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - profile
              - openid
              - email
          auth-server:
            client-id: "erp-api"
            client-secret: ${AUTH_SERVER_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/auth-server"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "client_secret_post"
            scope:
              - openid
              - profile
              - user.read
        provider:
          google:
            authorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenUri: https://oauth2.googleapis.com/token
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            userNameAttribute: sub
            jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
          auth-server:
            issuer-uri: http://127.0.0.1:8081
            user-info-uri: http://localhost:8082/userinfo


  datasource:
    url: jdbc:mysql://localhost:3306/human_capital_management_dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG