server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8081

  datasource:
    url: jdbc:mysql://localhost:3306/resource_server
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG