spring:
  security:
    oauth2:
      authorizationserver:
        client:
          erp-api:
            registration:
              client-id: "erp-api"
              client-secret: "{noop}secret"
              client-authentication-methods: "client_secret_post"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              scopes:
                - "openid"
                - "user.read"
                - "user.write"
                - "profile"
              redirect-uris: "http://localhost:8080/login/oauth2/code/auth-server"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
            require-authorization-consent: true

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
